[phases.setup]
nixPkgs = ['pnpm']

[phases.build]
cmds = [
  'cd $(wp theme path --allow-root --quiet --exec="error_reporting(0);")/$(wp option get stylesheet --allow-root --exec="error_reporting(0);") && pnpm install',
  'cd $(wp theme path --allow-root --quiet --exec="error_reporting(0);")/$(wp option get stylesheet --allow-root --exec="error_reporting(0);") && pnpm run dist'
]
