[variables]
NODE_ENV = 'production'

[phases.setup]
nixPkgs = ['wp-cli', "pnpm-8_x", "nodejs_18"]

[phases.build]
cmds = [
  'cd $(wp theme path --allow-root --quiet --exec="error_reporting(0);")/$(wp option get stylesheet --allow-root --exec="error_reporting(0);")',
  'pnpm install',
  'pnpm run dist'
]
