[variables]
NODE_ENV = 'production'

[phases.setup]
nixPkgs = ['wp-cli', "pnpm-8_x", "nodejs_18"]

[phases.build]
cmds = [
  'cd /app/web/app/themes/understrap-child && pnpm install',
  'cd /app/web/app/themes/understrap-child && pnpm run dist'
]
